import { Car } from '@/types/car';

export const CAR_DATA = [
  { label: 'Sport Car', value: 17439, color: '#0D3559' },
  { label: 'SUV', value: 9478, color: '#175D9C' },
  { label: 'Coupe', value: 18197, color: '#2185DE' },
  { label: 'Hatchback', value: 12510, color: '#63A9E8' },
  { label: 'MPV', value: 14406, color: '#A6CEF2' },
];

export const TOTAL_CARS = 120;

export const POPULAR_CARS: Car[] = [
  {
    name: 'Koenigsegg',
    type: 'Sport',
    steering: 'Manual',
    price: 99,
    capacity: 2,
    gasoline: 90,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: true,
    discount: 0,
    image: '/Koenigsegg.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'Nissan GT - R',
    type: 'Sport',
    steering: 'Manual',
    price: 80,
    capacity: 2,
    gasoline: 80,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: false,
    discount: 100,
    image: '/NissanGT-R.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'Rolls - Royce',
    type: 'Sedan',
    steering: 'Manual',
    price: 96,
    capacity: 4,
    gasoline: 70,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: true,
    discount: 0,
    image: '/RollsRoyce.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'Nissan GT - R',
    type: 'Sport',
    steering: 'Manual',
    price: 80,
    capacity: 2,
    gasoline: 80,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: false,
    discount: 100,
    image: '/NissanGT-R.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
];

export const RECOMMENDATION_CARS: Car[] = [
  {
    name: 'All New Rush',
    type: 'SUV',
    steering: 'Manual',
    price: 72,
    capacity: 6,
    gasoline: 70,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: false,
    discount: 80,
    image: '/AllNewRush.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'CR - V',
    type: 'SUV',
    steering: 'Manual',
    price: 80,
    capacity: 6,
    gasoline: 80,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: true,
    discount: 0,
    image: '/CR-V.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'All New Terios',
    type: 'SUV',
    steering: 'Manual',
    price: 74,
    capacity: 6,
    gasoline: 90,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: false,
    discount: 0,
    image: '/AllNewTerios.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'CR - V',
    type: 'SUV',
    steering: 'Manual',
    price: 80,
    capacity: 6,
    gasoline: 80,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: true,
    discount: 0,
    image: '/CR-V.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'MG ZX Exclusice',
    type: 'Hatchback',
    steering: 'Manual',
    price: 76,
    capacity: 4,
    gasoline: 70,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: true,
    discount: 80,
    image: '/MGZS.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'New MG ZS',
    type: 'SUV',
    steering: 'Manual',
    price: 80,
    capacity: 6,
    gasoline: 80,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: false,
    discount: 0,
    image: '/MGZS.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'MG ZX Excite',
    type: 'Hatchback',
    steering: 'Manual',
    price: 74,
    capacity: 4,
    gasoline: 90,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: true,
    discount: 80,
    image: '/MGZS.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
  {
    name: 'New MG ZS',
    type: 'SUV',
    steering: 'Manual',
    price: 80,
    capacity: 6,
    gasoline: 80,
    rate: 4.0,
    reviewer: 13,
    reviews: [],
    favorite: false,
    discount: 0,
    image: '/MGZS.svg',
    description: '',
    title: '',
    subtitle: '',
    thumbnails: [],
  },
];
