// Admin
export const ADMIN = {
  JWT_SECRET: "ADMIN_JWT_SECRET",
  API_TOKEN_SALT: "API_TOKEN_SALT",
  TRANSFER_TOKEN_SALT: "TRANSFER_TOKEN_SALT",
  ENCRYPTION_KEY: "ENCRYPTION_KEY",
  FLAG_NPS: "FLAG_NPS",
  FLAG_PROMOTE_EE: "FLAG_PROMOTE_EE",
} as const;

// Server
export const SERVER = {
  HOST: "HOST",
  PORT: "PORT",
  APP_KEYS: "APP_KEYS",
} as const;

// Database
export const DATABASE = {
  CLIENT: "DATABASE_CLIENT",
  HOST: "DATABASE_HOST",
  PORT: "DATABASE_PORT",
  NAME: "DATABASE_NAME",
  USERNAME: "DATABASE_USERNAME",
  PASSWORD: "DATABASE_PASSWORD",
  SSL: "DATABASE_SSL",
  SSL_KEY: "DATABASE_SSL_KEY",
  SSL_CERT: "DATABASE_SSL_CERT",
  SSL_CA: "DATABASE_SSL_CA",
  SSL_CAPATH: "DATABASE_SSL_CAPATH",
  SSL_CIPHER: "DATABASE_SSL_CIPHER",
  SSL_REJECT_UNAUTHORIZED: "DATABASE_SSL_REJECT_UNAUTHORIZED",
  SCHEMA: "DATABASE_SCHEMA",
  POOL_MIN: "DATABASE_POOL_MIN",
  POOL_MAX: "DATABASE_POOL_MAX",
  URL: "DATABASE_URL",
  FILENAME: "DATABASE_FILENAME",
  CONNECTION_TIMEOUT: "DATABASE_CONNECTION_TIMEOUT",
} as const;

export const ENV_DEFAULTS = {
  SERVER_PORT: 1337,
  SERVER_HOST: "0.0.0.0",
  DB_PORT: 3306,
  DB_HOST: "localhost",
  DB_NAME: "strapi",
  DB_USERNAME: "strapi",
  DB_PASSWORD: "strapi",
  DB_CLIENT: "sqlite",
  DB_POOL_MIN: 2,
  DB_POOL_MAX: 10,
  TIMEOUT: 60000,
} as const;

export const PAGE_SIZE_DEFAULTS = {
  POPULAR: 4,
  RECOMMENDATION: 8,
  MY_RENTALS: 10,
};
